-- Catálogo inicial de exámenes del laboratorio (sin precios: se cargan después)

INSERT INTO grupo_examen (id_grupo, nombre) VALUES (1, 'Hematología');
INSERT INTO grupo_examen (id_grupo, nombre) VALUES (2, 'Otros Exámenes');
INSERT INTO grupo_examen (id_grupo, nombre) VALUES (3, 'Misceláneos');
INSERT INTO grupo_examen (id_grupo, nombre) VALUES (5, 'Hormonas y Endocrinología');
INSERT INTO grupo_examen (id_grupo, nombre) VALUES (6, 'Serología e Inmunología');

INSERT INTO examen (id_grupo, nombre, muestra) VALUES (1, 'Dímero-D', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (1, 'Fibrinógeno', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (1, 'Frotis de Sangre Periférica', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (1, 'Hematología Completa', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (1, 'Químico Sanguíneo I', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (1, 'Químico Sanguíneo II', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (1, 'Tipo de Sangre (Carnet)', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (2, 'Antígenos Febriles', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (2, 'Coproanálisis', 'HECES');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (2, 'Cultivo de Orina', 'ORINA');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (2, 'Inmunología', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (2, 'Microalbuminuria en Orina Parcial', 'ORINA');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (2, 'Prueba de Embarazo', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (2, 'Serología de Donante', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (2, 'Uroanálisis', 'ORINA');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'Alfafetoproteínas', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'Anti-doping', 'ORINA');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'Antígeno Carcinoembrionario (C.E.A.)', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'Baciloscopia Seriada', 'ESPUTO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'CA 15-3', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'CA 19-9', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'CA-125', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'Creatinfosfoquinasa (CPK)', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'Curva de Tolerancia a la Glucosa', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'Eosinófilos en Moco Nasal', 'MOCO NASAL');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'Eosinófilos en Sangre', 'SANGRE TOTAL');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'Frotis de Flujo Vaginal', 'FLUJO VAGINAL');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'Inmunoglobulina E', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'Lactato Deshidrogenasa (LDH)', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'Monotest', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'P.S.A.', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (3, 'Vitamina D', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, '17 OH Progesterona', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, 'Androstenediona', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, 'Antitiroideos', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, 'Cortisol', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, 'DHEA', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, 'Estradiol', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, 'FSH', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, 'Gonadotropina Coriónica Cuantificada', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, 'Hemoglobina A1c', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, 'Insulina', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, 'LH', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, 'Perfil Tiroideo', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, 'Progesterona', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, 'Prolactina', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, 'TSH Ultra', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (5, 'Testosterona', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Anti-citomegalovirus', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Anti-toxoplasmosis', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Anticuerpos Antinucleares (ANA)', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Anticuerpos IgG Anti Varicela Zoster', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Dengue NS1', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'H.I.V. Test-Pack', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Helicobacter Pylori (Suero)', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Helicobacter Pylori en Heces', 'HECES');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Hepatitis A (IgM)', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Hepatitis A (Método Elisa)', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Hepatitis B (HBsAg)', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Hepatitis B Anti-HBs (Anticuerpos)', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Hepatitis C', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Herpes I y II', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Machado Guerreiro (Chagas)', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Mycoplasma Pneumoniae (IgG)', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Mycoplasma Pneumoniae (IgM)', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Serología Dengue', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Toxoplasmosis IgG Cuantitativa', 'SANGRE');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'V.D.R.L. y H.I.V.', 'SUERO');
INSERT INTO examen (id_grupo, nombre, muestra) VALUES (6, 'Virus del Epstein Barr (IgM)', 'SANGRE');
